config/routes.rb
Rails.application.routes.draw do

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up:'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	has_many :technologies, dependent: :destroy
	accepts_nested_attributes_for :technologies, 
																reject_if: lambda { |attrs| attrs['name'].blank? }
	include Placeholder
	validates_presence_of :title, :body

	mount_uploader :thumb_image, PortfolioUploader
	mount_uploader :main_image, PortfolioUploader

	def self.angular
		where(subtitle: 'Angular')
	end

	scope :ruby_on_rails, -> { where(subtitle: 'Ruby on Rails') }

	def self.by_position
		order("position ASC")
	end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [ :edit, :show, :update, :destroy ]
  layout 'portfolio'
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def show
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

	def index
    @portfolio_items = Portfolio.by_position
	end

	def new
    @portfolio_items = Portfolio.new
    3.times { @portfolio_items.technologies.build }
	end

	def edit
		@portfolio_items = Portfolio.find(params[:id])
	end

  def create
    @portfolio_items = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_items.save
        format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live!' }
      else
        format.html { render :new }
      end
    end
 end

   def update
   	@portfolio_items = Portfolio.find(params[:id])
   	
    respond_to do |format|
      if @portfolio_items.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio item was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    # Perform the lookup
    @portfolio_items = Portfolio.find(params[:id])
    # Destroy/Delete the record
    @portfolio_items.destroy
    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully deleted.' }
    end
  end

  private 

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle, 
                                      :body,
                                      :main_image,
                                      :thumb_image, 
                                      technologies_attributes: [:name]
                                      )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end	


	

app/helpers/portfolios_helper.rb
module PortfoliosHelper
	def image_generator(height:,width:)
		"http://via.placeholder.com/#{height}x#{width}"
	end

	def portfolio_img img, type
		if img
			img
		elsif type == 'thumb'
			image_generator(height: '350',width: '200')
			else
				image_generator(height: '600',width: '400')
		end
	end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_items) do |form| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_area :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
        Upload a main image file <%= form.file_field :main_image, style: 'display: none;' %>          
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
        Upload a thumb image file <%= form.file_field :thumb_image, style: 'display: none;' %>          
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>
  <div class = "col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= form.fields_for :technologies do |technology_form| %>
      <div class="form-group">
        <%= technology_form.label :name %>
        <%= technology_form.text_field :name, class: 'form-control' %>
      </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= form.submit "Save Portfolio Item", class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%= image_tag portfolio_img(portfolio_item.thumb_image.url, 'thumb') %>
  <p class="card-text">
  	<span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %> </span><%= portfolio_item.subtitle %>
  </p>
</div>
	
	

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_items.title, portfolio_show_path(portfolio_item) %></p>
	<p><%= portfolio_items.subtitle %></p>
	<p><%= portfolio_items.body %></p>
	<%= image_tag portfolio_items.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
	<%= link_to 'Delete Portfolio Item', portfolio_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' }  if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
	<h1>Edit your Portfolio item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
		
		<div class="row sortable">

			<%= render partial: 'portfolio_item', collection: @portfolio_items %>

		</div>
	</div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
	<h1>Create a new Portfolio item</h1>

	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag portfolio_img(@portfolio_item.thumb_image.url, 'main'), width: '100%' %>
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>

			<em><% @portfolio_item.subtitle %></em>

			<p><%= @portfolio_item.body %></p>

			<hr>

			<h3>Technologies Used:</h3>

			<% @portfolio_item.technologies.each do |t| %>
			<p><%= t.name %></p>
			<% end %>

		</div>
		<% if session[:user] = :site_admin %>
			<%= link_to "Edit", edit_portfolio_path %>
		<% end %>
	</div>
</div>